spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: order
    password: order2022
  redis:
    host: 127.0.0.1
    port: 6379
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
        show-sql: true

logging.level.org.hibernate.SQL: DEBUG

jwt:
  secret: V1hwS1YyRnRUblJXYWtKT1ZqTlNjMXBXVWt0TlYwcDBZa2hvYTFZeFZqWlplazVUWlZkSmVVNVhOVTlUUlRSNFYxUktUMkpIVFhwVQpWRVpxVFRCS05WbFdZekZpYXpWdVVGUXdQUW89